ApplicationLab.Web/Controllers/AirportCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplicationLab.Models.AirportData;
using ApplicationLab.Web.ViewModels;
using PagedList;
using PagedList.Mvc;

namespace ApplicationLab.Web.Controllers
{
    public class AirportCodesController : Controller
    {
        private AirportDataDB db = new AirportDataDB();

        // GET: AirportCodes
        public ActionResult Index(int? id, int? page, string currentFilter, string searchString, string filterOption, string sortBy, string sortOrder, string sortActive, string pSort, string pagingSort)
        {
            #region Initialize Variables
            AirportCodeIndexData viewModel = new AirportCodeIndexData();
            // To use Custom Stored Procedures use the following code instead:
            // db.Database.SqlQuery<AirportCode>("dbo.AirportCode_SelectAll").AsQueryable();
            IQueryable<AirportCode> qListAirportCodes = db.AirportCodes.AsQueryable().OrderBy(s => s.IATACode);
            string sortValue = string.Empty;
            #endregion
 
            #region search

            qListAirportCodes = SearchResult(qListAirportCodes, searchString, currentFilter, filterOption);

            #endregion

            #region Sorting
            if (string.IsNullOrEmpty(sortOrder))
            {
                ViewBag.sortOrder = string.IsNullOrEmpty(sortOrder) ? "_desc" : "";
            }

            if (sortActive == "1")
            {
                ViewBag.pSort = sortOrder;
            }
            else
            {
                ViewBag.pSort = pSort;
            }
            if (pagingSort == "1")
            {
                sortOrder = ViewBag.pSort;
                ViewBag.sortOrder = (sortOrder == "_desc" ? "" : "_desc");
            }

            ViewBag.sortBy = sortBy;
            
            sortValue = sortBy + sortOrder;

            switch (sortValue.ToLower())
            {
                case "iatacode":
                    qListAirportCodes = qListAirportCodes.OrderBy(s => s.IATACode);
                    break;
                case "iatacode_desc":
                    qListAirportCodes = qListAirportCodes.OrderByDescending(s => s.IATACode);
                    break;
                case "airportname":
                    qListAirportCodes = qListAirportCodes.OrderBy(s => s.AirportName);
                    break;
                case "airportname_desc":
                    qListAirportCodes = qListAirportCodes.OrderByDescending(s => s.AirportName);
                    break;
                default:
                    qListAirportCodes = qListAirportCodes.OrderBy(s => s.IATACode);
                    break;
            }
            #endregion

            #region Build Search Criteria Dropdown List

            List<SelectListItem> listFitlerOption = new List<SelectListItem>();
            listFitlerOption.Add(new SelectListItem { Value = "0", Text = "Search All..." });
            bool selectedValue = false;
            foreach (SearchCriteria sc in db.SearchCriterias)
            {
                if (filterOption != null)
                {
                    if (sc.ID.ToString().ToLower() == filterOption.ToLower())
                    {
                        selectedValue = true;
                    }
                }
                listFitlerOption.Add(new SelectListItem { Value = sc.ID.ToString(), Text = sc.FilteredItem, Selected = selectedValue });
                viewModel.ListSearchCriteria = listFitlerOption;
            }
            #endregion

            #region Paging
            int pageSize = 11;
            int pageNumber = (page ?? 1);
            ViewBag.ResultsCount = qListAirportCodes.Count();
            ViewBag.pageNumber = pageNumber;
            viewModel.ListAirportCode = qListAirportCodes.ToPagedList(pageNumber, pageSize);
            #endregion

            return View(viewModel);
        }

        // GET: AirportCodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportCode airportCode = db.AirportCodes.Find(id);
            if (airportCode == null)
            {
                return HttpNotFound();
            }
            return View(airportCode);
        }

        // GET: AirportCodes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AirportCodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AirportCodeID,IATACode,AirportName,City,Country")] AirportCode airportCode)
        {
            if (ModelState.IsValid)
            {
                db.AirportCodes.Add(airportCode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(airportCode);
        }

        // GET: AirportCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportCode airportCode = db.AirportCodes.Find(id);
            if (airportCode == null)
            {
                return HttpNotFound();
            }
            return View(airportCode);
        }

        // POST: AirportCodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AirportCodeID,IATACode,AirportName,City,Country")] AirportCode airportCode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(airportCode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(airportCode);
        }

        // GET: AirportCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportCode airportCode = db.AirportCodes.Find(id);
            if (airportCode == null)
            {
                return HttpNotFound();
            }
            return View(airportCode);
        }

        // POST: AirportCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AirportCode airportCode = db.AirportCodes.Find(id);
            db.AirportCodes.Remove(airportCode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IQueryable<AirportCode> FilteredResults(IQueryable<AirportCode> qListAirportCodes, string searchString, string filterOption)
        {
            List<AirportCode> listAirportCode = new List<AirportCode>();

            if (filterOption == "0")
            {
                listAirportCode = qListAirportCodes.Where(s => s.AirportName.Contains(searchString)
                                                                || s.City.Contains(searchString)
                                                                || s.Country.Contains(searchString)
                                                                || s.IATACode.Contains(searchString)

                ).ToList();
            }
            else if (filterOption == "1")
            {
                listAirportCode = qListAirportCodes.Where(s => s.IATACode.Contains(searchString)
                ).ToList();
            }
            else if (filterOption == "2")
            {
                listAirportCode = qListAirportCodes.Where(s => s.AirportName.Contains(searchString)
                ).ToList();
            }
            else if (filterOption == "3")
            {
                listAirportCode = qListAirportCodes.Where(s => s.City.Contains(searchString)
                ).ToList();
            }
            else if (filterOption == "4")
            {
                listAirportCode = qListAirportCodes.Where(s => s.Country.Contains(searchString)
                ).ToList();
            }
            return listAirportCode.AsQueryable();
        }

        private IQueryable<AirportCode> SearchResult(IQueryable<AirportCode> qListAirportCodes, string searchString, string currentFilter, string filterOption)
        {
            #region Search Feature
            if (searchString == null)
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilterOption = filterOption;
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                return FilteredResults(qListAirportCodes, searchString, filterOption);
            }
            else
            {
                return qListAirportCodes;
            }
            #endregion
        }

        //private IQueryable<AirportCode> SortResults(IQueryable<AirportCode> qListAirportCodes, )
        //{

        //}

    }
}

ApplicationLab.Web/Views/AirportCodes/Create.cshtml
@model ApplicationLab.Models.AirportData.AirportCode

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AirportCode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IATACode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IATACode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IATACode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AirportName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AirportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AirportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ApplicationLab.Web/Views/AirportCodes/Delete.cshtml
@model ApplicationLab.Models.AirportData.AirportCode

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AirportCode</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IATACode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IATACode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AirportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AirportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplicationLab.Web/Views/AirportCodes/Details.cshtml
@model ApplicationLab.Models.AirportData.AirportCode

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AirportCode</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IATACode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IATACode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AirportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AirportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AirportCodeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplicationLab.Web/Views/AirportCodes/Edit.cshtml
@model ApplicationLab.Models.AirportData.AirportCode

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AirportCode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AirportCodeID)

        <div class="form-group">
            @Html.LabelFor(model => model.IATACode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IATACode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IATACode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AirportName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AirportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AirportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ApplicationLab.Web/Views/AirportCodes/Index.cshtml
@model ApplicationLab.Web.ViewModels.AirportCodeIndexData
@using PagedList;
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Airport IATA Codes</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "AirportCodes", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-2">
            @Html.DropDownList("FilterOption", Model.ListSearchCriteria, htmlAttributes: new { @class = "form-control col-md-4 input-sm"})
        </div>
        <div class="col-md-4">
            @Html.TextBox("SearchString", (string)ViewBag.CurrentFilter, htmlAttributes: new { @class = "form-control col-md-4 input-sm"})
        </div>
        <div class="col-md-2">
            <input type="submit" value="Search" class="btn btn-default btn-sm" />
        </div>
    </div>
}
<br/>
<table class="table table-AS-striped table-AS-hover table-condensed">
    <tr>
        <th>
            @Html.ActionLink("IATACode", "Index", new { sortBy = "IATACode", sortOrder = ViewBag.sortOrder, currentFilter = ViewBag.CurrentFilter, filterOption = ViewBag.CurrentFilterOption, sortActive = "1", pSport = ViewBag.pSort, Page = ViewBag.pageNumber })
        </th>
        <th>
            @Html.ActionLink("Airport Name", "Index", new { sortBy = "AirportName", sortOrder = ViewBag.sortOrder, currentFilter = ViewBag.CurrentFilter, filterOption = ViewBag.CurrentFilterOption, sortActive = "1", pSport = ViewBag.pSort, Page = ViewBag.pageNumber })
        </th>
        <th>
            @Html.ActionLink("City", "Index", new { sortBy = "City", sortOrder = ViewBag.sortOrder, currentFilter = ViewBag.CurrentFilter, filterOption = ViewBag.CurrentFilterOption, sortActive = "1", pSport = ViewBag.pSort, Page = ViewBag.pageNumber })
        </th>
        <th>
            @Html.ActionLink("Country", "Index", new { sortBy = "Country", sortOrder = ViewBag.sortOrder, currentFilter = ViewBag.CurrentFilter, filterOption = ViewBag.CurrentFilterOption, sortActive = "1", pSport = ViewBag.pSort, Page = ViewBag.pageNumber })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.ListAirportCode)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IATACode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AirportName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.AirportCodeID }) |
            @Html.ActionLink("Details", "Details", new { id = item.AirportCodeID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.AirportCodeID })
        </td>
    </tr>
}

</table>

@Html.PagedListPager(Model.ListAirportCode, page => Url.Action("Index", new { page, filterOption = ViewBag.CurrentFilterOption, currentFilter = ViewBag.CurrentFilter, sortBy = ViewBag.sortBy, pagingSort = "1", pSort = ViewBag.pSort}))
Page @(Model.ListAirportCode.PageCount < Model.ListAirportCode.PageNumber ? 0 : Model.ListAirportCode.PageNumber) of @Model.ListAirportCode.PageCount

@section Scripts
{
    <link rel="stylesheet" href="~/Content/JQueryUI/jquery-ui.css" />
    <script type="text/javascript" src="~/Scripts/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script>
        var url = '@Url.RouteUrl("DefaultApi", new
             {
                 httproute = "", controller = "AirportCodesApi"
             })';
        $("#SearchString").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: url,
                    data: { filterOption: $("#FilterOption").val(), query: request.term,},
                    datatype: 'json',
                    type: 'GET',
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                label: item.SearchResult,
                                value: item.Id
                            }
                        }));
                    }

                })
            },

            minlength: 1
        });

    </script>
    }